services:

  dictionary-mongodb:
    image: mongo
    container_name: dictionary-mongodb
    stop_signal: SIGINT
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb/words.json:/docker-entrypoint-initdb.d/words.json:ro
    command: mongod --auth 
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host

