services:

  dictionary-mongodb:
    image: mongo
    container_name: dictionary-mongodb
    stop_signal: SIGINT
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: admin
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb/words.json:/docker-entrypoint-initdb.d/words.json:ro
    command: mongod --auth 
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dictionary-network

  dictionary-backend:
    image: dictionary-backend
    build: 
      context:
        ./backend
    stop_signal: SIGINT
    restart: always
    container_name: dictionary-backend
    ports:
      - "5000:5000"
    depends_on:
      - dictionary-mongodb
    networks:
      - dictionary-network

  dictionary-nginx:
    image: dictionary-nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: dictionary-nginx
    ports:
      - "3001:3001"
    networks:
      - dictionary-network

networks:
  dictionary-network:
    driver: bridge
